#!/bin/bash

## SLURM script used to compile ibpf-tutorial/ms.pdf 
## on the University of Michigan greatlakes cluster
## run:  sbatch sbat

#SBATCH --job-name=ibpf-tutorial
#SBATCH --mail-user=ionides@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL
 
#SBATCH --account=ionides0
#SBATCH --partition=standard

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --cpus-per-task=1

## 5GB/cpu is the basic share
#SBATCH --mem-per-cpu=5GB

## run time: 8:50 hr on 24-08-06 for commit be027722e2cf
## wall time hours:minutes:seconds
#SBATCH --time=15:00:00

###   Load software modules

module load R
module list

####  Commands your job should run follow this line

echo "Running on $SLURM_JOB_NODELIST"
echo "Running in $(pwd)"

Rscript --no-save --no-restore --no-init-file -e "knitr::knit(\"ms.Rnw\")" > ms.Rout 2>&1

